services:
  frontend:
    build: ./sefaz-gateway-frontend
    ports:
      - "4200:80"
    depends_on:
      - mock-server

  mock-server:
    image: mockserver/mockserver:mockserver-5.15.0
    container_name: meu_mockserver
    user: root
    ports:
      - "1080:1080"
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json
    volumes:
      - ./gateway-sefaz-mockserver/config:/config
